### ISSUE TITLE
strangly shows temp of video

### ISSUE THREAD

**Issue by fufar** [brianberg/ha-nicehash#6]
## Version of the custom_component

72543f6 ? latest
## Configuration

2021.5.3, docker, debian

## Describe the bug
![image](https://user-images.githubusercontent.com/22238388/118289263-d472d680-b4dd-11eb-962e-bec0fc36acd2.png)
![image](https://user-images.githubusercontent.com/22238388/118289288-ddfc3e80-b4dd-11eb-8e33-80bd77e94921.png)
This is not my gpu temp. This is sun temp or whatever :)

I have only 1 gpu so cant say - it is problem for one or all

**Comment by tcate03** [comment]
i have the same issue. excavator temp reads as 4718652*C

**Comment by agoncalvesos** [comment]
I have the same :) Do we need to device the value by 100.000? :D

**Comment by fufar** [comment]
for me divison by 100000 wouldnt work - numbers are different
may be there is a way to test throu api what nicehash data recives - and understand where error is?
@brianberg  any ideas?

**Comment by fufar** [comment]
ok, found that addon based on https://github.com/nicehash/rest-clients-demo
find issue https://github.com/nicehash/rest-clients-demo/issues/29
temp must be divided by 65536
for me it gives right temp

**Comment by fufar** [comment]
@tcate03 @agoncalvesos try this pls, if il work ok - i will make a pr

**Comment by brianberg** [comment]
`%` is the modulus operator. I'm curious to understand why that's necessary. It seems as though the NiceHash API is giving you the wrong value. What is the significance of `65536`?

**Comment by brianberg** [comment]
Did NiceHash change their API responses for GPU temps? Seems like an easy change to make to the integration but I don't want to break it for everyone else.

**Comment by fufar** [comment]
dont know why, found it here https://github.com/nicehash/rest-clients-demo/issues/29
may be some difference between nice hash versions( i  use quick miner) or between versions of program?

**Comment by brianberg** [comment]
@fufar I think you're right, it's a QuickMiner thing

https://github.com/nicehash/NiceHashQuickMiner/issues/146

**Comment by brianberg** [comment]
It's been a long time since I've even thought about unsigned integers 😆

**Comment by fufar** [comment]
ok, so can you make some fix?

**Comment by brianberg** [comment]
I need to get my local test setup working again, but I _think_ I can get a fix out for this, this week

**Comment by fufar** [comment]
tryed, looks like working ok for me

**Comment by brianberg** [comment]
Latest version `0.1.1` should fix this issue, I'll leave this open until it's confirmed

**Comment by fufar** [comment]
for me - ok
@tcate03 @agoncalvesos ?

**Comment by tcate03** [comment]
negative. Still seeing excavator temps of 65,535 C

**Comment by andrewhair** [comment]
Negative for me too, but at least the number is not as big.

**Comment by agoncalvesos** [comment]
@fufar using the low_temperature property works for me :) I have temperatures of 57ºC
